spring:
  application:
    name: user-access-permission
  datasource:
    url: jdbc:h2:file:./testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: pass
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
application:
  password:
    pattern: '^(?=.*[a-zA-Z])(?=.*[0-9]).{8,}$'

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
